name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y at-spi2-core libcairo-dev libgee-0.8-dev libgtk-4-dev meson valac xvfb

      - name: Build
        env:
          DESTDIR: out
        run: |
          meson setup build -Ddebug=true -Db_coverage=true
          ninja -C build install

      - name: Run tests
        run: |
            meson test -C build || ([[ -f /home/runner/work/live-chart/live-chart/build/meson-logs/testlog-xvfb-run.txt ]] && cat /home/runner/work/live-chart/live-chart/build/meson-logs/testlog-xvfb-run.txt && exit 1)

  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: io.elementary.vala-lint -d .
